# Generated by Django 3.2.8 on 2021-10-14 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DonationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DonorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.CharField(max_length=40)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=4)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('last_donate_date', models.CharField(max_length=50)),
                ('any_diseases', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4)),
                ('bleeding_disorders', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4)),
                ('near_hospital', models.CharField(choices=[('Khulna City Medical', 'Khulna City Medical'), ('Khulna Medical College Hospital', 'Khulna Medical College Hospital'), ('Khulna Sadar Hospital', 'Khulna Sadar Hospital'), ('Islami Bank Hospital', 'Islami Bank Hospital'), ('SANDHANI DONOR CLUB KHULNA', 'SANDHANI DONOR CLUB KHULNA'), ('Khulna Healthcare Hospital', 'Khulna Healthcare Hospital'), ('Surokkha Hospital & Diagnostic', 'Surokkha Hospital & Diagnostic')], default='Khulna Medical College Hospital', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('photos', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ShareExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_feeling', models.TextField()),
                ('share_image', models.ImageField(upload_to='share_image')),
                ('log_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
