# Generated by Django 3.2.8 on 2021-10-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregister',
            name='today_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
