# Generated by Django 3.2.8 on 2021-10-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_remove_shareexperience_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareexperience',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
