# Generated by Django 3.2.8 on 2021-10-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_shareexperience_is_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareExperience',
        ),
    ]
