# Generated by Django 3.2.8 on 2021-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_delete_shareexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('share_message', models.TextField()),
                ('share_image', models.ImageField(upload_to='share_image')),
            ],
        ),
    ]
