# Generated by Django 3.2.8 on 2021-10-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_shareus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareUS',
        ),
    ]
