# Generated by Django 3.2.8 on 2021-10-31 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_delete_shareus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='donorregister',
            name='near_hospital',
            field=models.ForeignKey(default='Khulna Medical College Hospital', on_delete=django.db.models.deletion.CASCADE, to='frontpage.hospital'),
        ),
    ]
