# Generated by Django 3.2.8 on 2021-10-31 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_auto_20211101_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregister',
            name='near_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.hospital'),
        ),
    ]
