# Generated by Django 3.2.8 on 2021-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_alter_donorregister_near_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
